// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	protos.proto

It has these top-level messages:
	PBMessage
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PBMessage_MessageType int32

const (
	PBMessage_Unknown PBMessage_MessageType = 0
	PBMessage_Join    PBMessage_MessageType = 1
	PBMessage_Leave   PBMessage_MessageType = 2
	PBMessage_NewChat PBMessage_MessageType = 3
)

var PBMessage_MessageType_name = map[int32]string{
	0: "Unknown",
	1: "Join",
	2: "Leave",
	3: "NewChat",
}
var PBMessage_MessageType_value = map[string]int32{
	"Unknown": 0,
	"Join":    1,
	"Leave":   2,
	"NewChat": 3,
}

func (x PBMessage_MessageType) String() string {
	return proto.EnumName(PBMessage_MessageType_name, int32(x))
}
func (PBMessage_MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type PBMessage struct {
	Type    PBMessage_MessageType `protobuf:"varint,1,opt,name=type,enum=pb.PBMessage_MessageType" json:"type,omitempty"`
	Name    string                `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Message string                `protobuf:"bytes,3,opt,name=Message" json:"Message,omitempty"`
}

func (m *PBMessage) Reset()                    { *m = PBMessage{} }
func (m *PBMessage) String() string            { return proto.CompactTextString(m) }
func (*PBMessage) ProtoMessage()               {}
func (*PBMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PBMessage) GetType() PBMessage_MessageType {
	if m != nil {
		return m.Type
	}
	return PBMessage_Unknown
}

func (m *PBMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PBMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*PBMessage)(nil), "pb.PBMessage")
	proto.RegisterEnum("pb.PBMessage_MessageType", PBMessage_MessageType_name, PBMessage_MessageType_value)
}

func init() { proto.RegisterFile("protos.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x03, 0x53, 0x42, 0x4c, 0x05, 0x49, 0x4a, 0xcb, 0x18, 0xb9, 0x38, 0x03, 0x9c,
	0x7c, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x74, 0xb9, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25,
	0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0x24, 0xf5, 0x0a, 0x92, 0xf4, 0xe0, 0x92, 0x7a, 0x50, 0x3a,
	0x04, 0xa8, 0x20, 0x08, 0xac, 0x4c, 0x48, 0x88, 0x8b, 0xc5, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x09,
	0xa8, 0x9c, 0x33, 0x08, 0xcc, 0x16, 0x92, 0xe0, 0x62, 0x87, 0x2a, 0x94, 0x60, 0x06, 0x0b, 0xc3,
	0xb8, 0x4a, 0x36, 0x5c, 0xdc, 0x48, 0x46, 0x08, 0x71, 0x73, 0xb1, 0x87, 0xe6, 0x65, 0xe7, 0xe5,
	0x97, 0xe7, 0x09, 0x30, 0x08, 0x71, 0x70, 0xb1, 0x78, 0xe5, 0x67, 0xe6, 0x09, 0x30, 0x0a, 0x71,
	0x72, 0xb1, 0xfa, 0xa4, 0x26, 0x96, 0xa5, 0x0a, 0x30, 0x81, 0x54, 0xf8, 0xa5, 0x96, 0x3b, 0x67,
	0x24, 0x96, 0x08, 0x30, 0x27, 0xb1, 0x81, 0xdd, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xfc,
	0x0f, 0xfc, 0xe6, 0xc3, 0x00, 0x00, 0x00,
}
