// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	protos.proto

It has these top-level messages:
	PBMessage
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PBMessage_MessageType int32

const (
	PBMessage_Unknown       PBMessage_MessageType = 0
	PBMessage_Join          PBMessage_MessageType = 1
	PBMessage_Leave         PBMessage_MessageType = 2
	PBMessage_NewChat       PBMessage_MessageType = 3
	PBMessage_StartingState PBMessage_MessageType = 4
)

var PBMessage_MessageType_name = map[int32]string{
	0: "Unknown",
	1: "Join",
	2: "Leave",
	3: "NewChat",
	4: "StartingState",
}
var PBMessage_MessageType_value = map[string]int32{
	"Unknown":       0,
	"Join":          1,
	"Leave":         2,
	"NewChat":       3,
	"StartingState": 4,
}

func (x PBMessage_MessageType) String() string {
	return proto.EnumName(PBMessage_MessageType_name, int32(x))
}
func (PBMessage_MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type PBMessage struct {
	Type     PBMessage_MessageType `protobuf:"varint,1,opt,name=type,enum=pb.PBMessage_MessageType" json:"type,omitempty"`
	Name     string                `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Message  string                `protobuf:"bytes,3,opt,name=Message" json:"Message,omitempty"`
	Messages []string              `protobuf:"bytes,4,rep,name=Messages" json:"Messages,omitempty"`
}

func (m *PBMessage) Reset()                    { *m = PBMessage{} }
func (m *PBMessage) String() string            { return proto.CompactTextString(m) }
func (*PBMessage) ProtoMessage()               {}
func (*PBMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PBMessage) GetType() PBMessage_MessageType {
	if m != nil {
		return m.Type
	}
	return PBMessage_Unknown
}

func (m *PBMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PBMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PBMessage) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*PBMessage)(nil), "pb.PBMessage")
	proto.RegisterEnum("pb.PBMessage_MessageType", PBMessage_MessageType_name, PBMessage_MessageType_value)
}

func init() { proto.RegisterFile("protos.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x03, 0x53, 0x42, 0x4c, 0x05, 0x49, 0x4a, 0x57, 0x19, 0xb9, 0x38, 0x03, 0x9c,
	0x7c, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x74, 0xb9, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25,
	0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0x24, 0xf5, 0x0a, 0x92, 0xf4, 0xe0, 0x92, 0x7a, 0x50, 0x3a,
	0x04, 0xa8, 0x20, 0x08, 0xac, 0x4c, 0x48, 0x88, 0x8b, 0xc5, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x09,
	0xa8, 0x9c, 0x33, 0x08, 0xcc, 0x16, 0x92, 0xe0, 0x62, 0x87, 0x2a, 0x94, 0x60, 0x06, 0x0b, 0xc3,
	0xb8, 0x42, 0x52, 0x5c, 0x1c, 0x50, 0x66, 0xb1, 0x04, 0x8b, 0x02, 0x33, 0x50, 0x0a, 0xce, 0x57,
	0xf2, 0xe7, 0xe2, 0x46, 0x32, 0x5e, 0x88, 0x9b, 0x8b, 0x3d, 0x34, 0x2f, 0x3b, 0x2f, 0xbf, 0x3c,
	0x4f, 0x80, 0x41, 0x88, 0x83, 0x8b, 0xc5, 0x2b, 0x3f, 0x33, 0x4f, 0x80, 0x51, 0x88, 0x93, 0x8b,
	0xd5, 0x27, 0x35, 0xb1, 0x2c, 0x55, 0x80, 0x09, 0xa4, 0xc2, 0x2f, 0xb5, 0xdc, 0x39, 0x23, 0xb1,
	0x44, 0x80, 0x59, 0x48, 0x90, 0x8b, 0x37, 0xb8, 0x24, 0xb1, 0xa8, 0x24, 0x33, 0x2f, 0x1d, 0x48,
	0x97, 0xa4, 0x0a, 0xb0, 0x24, 0xb1, 0x81, 0xbd, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x83,
	0x78, 0x64, 0xa6, 0xf2, 0x00, 0x00, 0x00,
}
